# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: 'ckeditor'
    js_path: 'ckeditor/ckeditor.js'
    configs:
        main_config:
            filebrowserBrowseRoute: file_manager
            filebrowserBrowseRouteParameters:
                conf: default
                module: ckeditor