twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: "Nom du site"
        version: "1.2"
        date_update: "04/07/2023"
        google_maps: ""
        recaptcha_public: ''
        recaptcha_private: ''
        mailjet_public: ''
        mailjet_private: ''
        posts_img_directory: '/uploads/images/posts'

when@test:
    twig:
        strict_variables: true
