twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%env(SITE_NAME)%'
        version: "2.9"
        date_update: "28/11/2023"
        google_maps: ""
        recaptcha_public: ''
        recaptcha_private: ''
        mailjet_public: ''
        mailjet_private: ''
        posts_img_directory: '/uploads/images/posts'

when@test:
    twig:
        strict_variables: true
