# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.jwtsecret: '%env(JWT_SECRET)%'
    posts_img_directory: '%kernel.project_dir%/public/uploads/images/posts'
    mysqldump_path: '%env(MYSQL_DUMP)%'
    css_js_directory: '%kernel.project_dir%/public/build'
    css_js_path: 'app_65873a0311d3c'
    googleClientId: '%env(CLIENT_ID)%'
    googleClientSecret: '%env(CLIENT_SECRET)%'
    site_name: '%env(SITE_NAME)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Services\BackupService:
        arguments:
            $databaseUrl: '%env(DATABASE_URL)%'
    
    App\Command\BackupDatabaseCommand:
        arguments:
            $backupService: '@App\Services\BackupService'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
